hash-format = "sha256"

[[files]]
file = "mods/addadd.pw.toml"
hash = "5dac19e31a3f315c9ea761268ce63c8c1ba87b3b773e9b6827f5b4f66b59b24f"
metafile = true

[[files]]
file = "mods/annotated-di.pw.toml"
hash = "2c293a5a3cd620cedc6cc07f3691f7d2b32cc2881a4cec82b321d7e343568cc1"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "14b1a9c6c6f2a0c87189602f9ccce3e3535bab850a0c93e1467312ff5dd1cd86"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5f92380ca786cd96438d67661e656547ce89d02b19bafe1c71031fbf2ca0bf98"
metafile = true

[[files]]
file = "mods/axes-are-weapons.pw.toml"
hash = "aca3f83f2545b655b24e6807a11ebe5f161c5beed8828d35493fd3b546bbc86e"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "7da74fd4dc94275df9345369417dd6314076b69fb92a32846b9bb95f4e9eb0d4"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "d327839546f676861ab40202cf9b1a20bea90950e80231e7df2f5631fa115bb3"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "ee868e7edfb76bc7cc9e50970d33f37fbabbd5219b86fff38d9ec8e1bb15fd4a"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "70033587920b8d52692b85745093362a789c1167216bb79ebb7852d431e83598"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "d32925cc3cd59d5dba62722f87e0efb4d149f45fd492f0374a72537c6ff99a75"
metafile = true

[[files]]
file = "mods/dynamic-lights.pw.toml"
hash = "4a7d6830de80e0d466d9e5841916c02fbefd45b64a146ada34db7d5de97c2999"
metafile = true

[[files]]
file = "mods/fireplace-lib.pw.toml"
hash = "c8d076ba2b067ed7f151381293259b8df3118bffcffa42e9e298fa513f27ce82"
metafile = true

[[files]]
file = "mods/flywheel.pw.toml"
hash = "ecf724b67501ed0a91109a1264aa6e803f6ea028e8fb6f6af3ca4ace790dc0d2"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "805dded546acbf94889d96bceacb5496f7e84054dfd7a00b1970968522287ad1"
metafile = true

[[files]]
file = "mods/origins-classes-forge.pw.toml"
hash = "b1b777bdbd72ce68ea271678983e83a2c539bec5bd48e1c7b78b3f30fcfbe985"
metafile = true

[[files]]
file = "mods/origins-forge.pw.toml"
hash = "b69342578f4bbbb1cfa56fac4b2f57c7654de74bb01c49bd1cc49d6bb7bac219"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "881c91d7f922844d3922004223bccd76feeb2c04963be86a42ac3ac950c3da1e"
metafile = true

[[files]]
file = "mods/starlight-forge.pw.toml"
hash = "45e3cee1482b218c905eb2e2bcdbb15f4843039bffdcb0a7ce1a742aecbcb93e"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
hash = "456490e6c0532199615f7fd74956066c39b400dd1b9cdd05dc9566fa43d545c5"
metafile = true

[[files]]
file = "mods/unforgiving-void.pw.toml"
hash = "2ef2a24e7062046d615cab41f0be1e797c913f9fe811a0fbe7d424285b07765e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "34705769206c43cfec5efbdfa03e83c8e45760f01bef03148d9bfc2ccc0b7360"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "1f8cc9461ca4df22deffc40d785cfde26f4e04e1a2759601d4638d84ceaa8f38"
metafile = true
